// Barbell affiliate URL - TruGrit Fitness
export const BARBELL_AFFILIATE_URL = 'https://trugritfitness.pxf.io/Z6PKV1';

// Supplement affiliate URL - Muscle & Strength
export const SUPPLEMENT_AFFILIATE_URL = 'https://www.jdoqocy.com/click-101430101-15734183';

// Mock data for development (before Supabase is set up)
export const MOCK_BARBELLS = [
  {
    id: '1',
    name: 'Rogue Ohio Bar',
    brand: 'Rogue',
    slug: 'rogue-ohio-bar',
    weight: 20,
    weight_lbs: 45,
    tensile_strength: 190000,
    coating: 'black zinc',
    sleeve_rotation: true,
    price: 295,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 4.8,
    reviews_count: 1247,
    category: 'olympic',
  },
  {
    id: '2',
    name: 'Eleiko Olympic Weightlifting Bar',
    brand: 'Eleiko',
    slug: 'eleiko-olympic-bar',
    weight: 20,
    weight_lbs: 45,
    tensile_strength: 215000,
    coating: 'chrome',
    sleeve_rotation: true,
    price: 795,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 4.9,
    reviews_count: 892,
    category: 'olympic',
  },
  {
    id: '3',
    name: 'CAP Barbell 20kg Bar',
    brand: 'CAP',
    slug: 'cap-barbell-20kg',
    weight: 20,
    weight_lbs: 45,
    tensile_strength: 150000,
    coating: 'chrome',
    sleeve_rotation: true,
    price: 129,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 4.2,
    reviews_count: 2341,
    category: 'olympic',
  },
  {
    id: '4',
    name: 'REP Fitness Power Bar',
    brand: 'REP',
    slug: 'rep-fitness-power-bar',
    weight: 20,
    weight_lbs: 45,
    tensile_strength: 205000,
    coating: 'black oxide',
    sleeve_rotation: true,
    price: 349,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 4.7,
    reviews_count: 567,
    category: 'powerlifting',
  },
  {
    id: '5',
    name: 'Rogue Boneyard Bar',
    brand: 'Rogue',
    slug: 'rogue-boneyard-bar',
    weight: 20,
    weight_lbs: 45,
    tensile_strength: 190000,
    coating: 'cerakote',
    sleeve_rotation: true,
    price: 275,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 4.6,
    reviews_count: 445,
    category: 'olympic',
  },
  {
    id: '6',
    name: "Women's Training Bar 15kg",
    brand: 'Rogue',
    slug: 'rogue-womens-training-bar',
    weight: 15,
    weight_lbs: 33,
    tensile_strength: 160000,
    coating: 'stainless steel',
    sleeve_rotation: true,
    price: 245,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 4.5,
    reviews_count: 234,
    category: 'women',
  },
  {
    id: '7',
    name: 'Eleiko Sport Training Bar',
    brand: 'Eleiko',
    slug: 'eleiko-sport-training-bar',
    weight: 20,
    weight_lbs: 45,
    tensile_strength: 200000,
    coating: 'black',
    sleeve_rotation: true,
    price: 545,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1517963879466-cd115eb9dbbe?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 4.8,
    reviews_count: 312,
    category: 'crossfit',
  },
  {
    id: '8',
    name: 'REP PR-4000 Bar',
    brand: 'REP',
    slug: 'rep-pr-4000-bar',
    weight: 20,
    weight_lbs: 45,
    tensile_strength: 190000,
    coating: 'black zinc',
    sleeve_rotation: true,
    price: 299,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 4.6,
    reviews_count: 678,
    category: 'crossfit',
  },
  {
    id: '9',
    name: 'CAP Basic Bar',
    brand: 'CAP',
    slug: 'cap-basic-bar',
    weight: 20,
    weight_lbs: 45,
    tensile_strength: 140000,
    coating: 'chrome',
    sleeve_rotation: true,
    price: 99,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 4.0,
    reviews_count: 1567,
    category: 'olympic',
  },
  {
    id: '10',
    name: 'Rogue Euro Bar',
    brand: 'Rogue',
    slug: 'rogue-euro-bar',
    weight: 20,
    weight_lbs: 45,
    tensile_strength: 215000,
    coating: 'nickel',
    sleeve_rotation: true,
    price: 395,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 4.9,
    reviews_count: 234,
    category: 'olympic',
  },
  {
    id: '11',
    name: 'Eleiko Power Bar',
    brand: 'Eleiko',
    slug: 'eleiko-power-bar',
    weight: 20,
    weight_lbs: 45,
    tensile_strength: 220000,
    coating: 'chrome',
    sleeve_rotation: true,
    price: 895,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 5.0,
    reviews_count: 156,
    category: 'powerlifting',
  },
  {
    id: '12',
    name: 'REP Exceed Bar',
    brand: 'REP',
    slug: 'rep-exceed-bar',
    weight: 20,
    weight_lbs: 45,
    tensile_strength: 200000,
    coating: 'cerakote',
    sleeve_rotation: true,
    price: 449,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1517963879466-cd115eb9dbbe?w=400',
    affiliate_url: BARBELL_AFFILIATE_URL,
    rating: 4.7,
    reviews_count: 289,
    category: 'powerlifting',
  },
];

export const MOCK_BRANDS = [
  { 
    id: '1', 
    name: 'Rogue', 
    slug: 'rogue', 
    logo_url: '', 
    website: 'https://trugritfitness.pxf.io/Z6PKV1', 
    description: 'American-made fitness equipment',
    country: 'USA',
    founded: 2007,
    specialty: 'Commercial & Home Gym',
  },
  { 
    id: '2', 
    name: 'Eleiko', 
    slug: 'eleiko', 
    logo_url: '', 
    website: 'https://trugritfitness.pxf.io/Z6PKV1', 
    description: 'Swedish quality since 1957',
    country: 'Sweden',
    founded: 1957,
    specialty: 'Competition Equipment',
  },
  { 
    id: '3', 
    name: 'CAP', 
    slug: 'cap', 
    logo_url: '', 
    website: 'https://trugritfitness.pxf.io/Z6PKV1', 
    description: 'Affordable fitness equipment',
    country: 'USA',
    founded: 1990,
    specialty: 'Budget-Friendly',
  },
  { 
    id: '4', 
    name: 'REP', 
    slug: 'rep', 
    logo_url: '', 
    website: 'https://trugritfitness.pxf.io/Z6PKV1', 
    description: 'Premium home gym equipment',
    country: 'USA',
    founded: 2012,
    specialty: 'Home Gym Specialist',
  },
  { 
    id: '5', 
    name: 'TruGrit Fitness', 
    slug: 'trugrit', 
    logo_url: '', 
    website: 'https://trugritfitness.pxf.io/Z6PKV1', 
    description: 'Your trusted fitness equipment partner',
    country: 'USA',
    founded: 2015,
    specialty: 'Affiliate Partner',
  },
];

export const MOCK_CITIES = [
  { id: '1', name: 'New York', state: 'NY', country: 'USA', slug: 'new-york', lat: 40.7128, lng: -74.006, population: '8.4M' },
  { id: '2', name: 'Los Angeles', state: 'CA', country: 'USA', slug: 'los-angeles', lat: 34.0522, lng: -118.2437, population: '3.9M' },
  { id: '3', name: 'Chicago', state: 'IL', country: 'USA', slug: 'chicago', lat: 41.8781, lng: -87.6298, population: '2.7M' },
  { id: '4', name: 'London', state: '', country: 'UK', slug: 'london', lat: 51.5074, lng: -0.1278, population: '8.8M' },
  { id: '5', name: 'Miami', state: 'FL', country: 'USA', slug: 'miami', lat: 25.7617, lng: -80.1918, population: '450K' },
  { id: '6', name: 'Houston', state: 'TX', country: 'USA', slug: 'houston', lat: 29.7604, lng: -95.3698, population: '2.3M' },
  { id: '7', name: 'Phoenix', state: 'AZ', country: 'USA', slug: 'phoenix', lat: 33.4484, lng: -112.074, population: '1.7M' },
  { id: '8', name: 'Seattle', state: 'WA', country: 'USA', slug: 'seattle', lat: 47.6062, lng: -122.3321, population: '750K' },
  { id: '9', name: 'Denver', state: 'CO', country: 'USA', slug: 'denver', lat: 39.7392, lng: -104.9903, population: '715K' },
  { id: '10', name: 'Toronto', state: 'ON', country: 'Canada', slug: 'toronto', lat: 43.6532, lng: -79.3832, population: '2.9M' },
];

export const MOCK_SUPPLEMENTS = [
  {
    id: 's1',
    name: 'Whey Protein Isolate',
    brand: 'Muscle & Strength',
    slug: 'whey-protein-isolate',
    category: 'protein',
    price: 49.99,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400',
    affiliate_url: SUPPLEMENT_AFFILIATE_URL,
    rating: 4.7,
    reviews_count: 892,
    description: 'Premium whey protein isolate for muscle recovery and growth.',
  },
  {
    id: 's2',
    name: 'Creatine Monohydrate',
    brand: 'Muscle & Strength',
    slug: 'creatine-monohydrate',
    category: 'performance',
    price: 24.99,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400',
    affiliate_url: SUPPLEMENT_AFFILIATE_URL,
    rating: 4.8,
    reviews_count: 1247,
    description: 'Pure creatine monohydrate for strength and power.',
  },
  {
    id: 's3',
    name: 'Pre-Workout Extreme',
    brand: 'Muscle & Strength',
    slug: 'pre-workout-extreme',
    category: 'pre-workout',
    price: 39.99,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400',
    affiliate_url: SUPPLEMENT_AFFILIATE_URL,
    rating: 4.5,
    reviews_count: 567,
    description: 'Explosive energy and focus for intense workouts.',
  },
  {
    id: 's4',
    name: 'BCAA Recovery',
    brand: 'Muscle & Strength',
    slug: 'bcaa-recovery',
    category: 'recovery',
    price: 29.99,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400',
    affiliate_url: SUPPLEMENT_AFFILIATE_URL,
    rating: 4.6,
    reviews_count: 445,
    description: 'Branch chain amino acids for optimal recovery.',
  },
  {
    id: 's5',
    name: 'Casein Protein',
    brand: 'Muscle & Strength',
    slug: 'casein-protein',
    category: 'protein',
    price: 54.99,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400',
    affiliate_url: SUPPLEMENT_AFFILIATE_URL,
    rating: 4.4,
    reviews_count: 234,
    description: 'Slow-digesting protein perfect for nighttime recovery.',
  },
  {
    id: 's6',
    name: 'Fish Oil Omega-3',
    brand: 'Muscle & Strength',
    slug: 'fish-oil-omega3',
    category: 'health',
    price: 19.99,
    currency: 'USD',
    image_url: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400',
    affiliate_url: SUPPLEMENT_AFFILIATE_URL,
    rating: 4.6,
    reviews_count: 678,
    description: 'Essential omega-3 fatty acids for heart and joint health.',
  },
];

// Helper functions
export function getBarbellsByBrand(brand: string) {
  return MOCK_BARBELLS.filter(b => b.brand.toLowerCase() === brand.toLowerCase());
}

export function getBarbellsByCategory(category: string) {
  return MOCK_BARBELLS.filter(b => b.category === category);
}

export function getBarbellsByPriceRange(min: number, max: number) {
  return MOCK_BARBELLS.filter(b => b.price >= min && b.price <= max);
}

export function sortBarbells(sortBy: string) {
  const sorted = [...MOCK_BARBELLS];
  switch (sortBy) {
    case 'price-asc': return sorted.sort((a, b) => a.price - b.price);
    case 'price-desc': return sorted.sort((a, b) => b.price - a.price);
    case 'rating': return sorted.sort((a, b) => b.rating - a.rating);
    case 'tensile': return sorted.sort((a, b) => b.tensile_strength - a.tensile_strength);
    default: return sorted;
  }
}

export function getSupplementsByCategory(category: string) {
  return MOCK_SUPPLEMENTS.filter(s => s.category === category);
}

export function sortSupplements(sortBy: string) {
  const sorted = [...MOCK_SUPPLEMENTS];
  switch (sortBy) {
    case 'price-asc': return sorted.sort((a, b) => a.price - b.price);
    case 'price-desc': return sorted.sort((a, b) => b.price - a.price);
    case 'rating': return sorted.sort((a, b) => b.rating - a.rating);
    default: return sorted;
  }
}
